const EMAIL_MAX_ATTEMPTS = process.env.EMAIL_MAX_ATTEMPTS;
const PAYMENT_MAX_ATTEMPTS = process.env.PAYMENT_MAX_ATTEMPTS;
const NOTIFICATION_MAX_ATTEMPTS = process.env.NOTIFICATION_MAX_ATTEMPTS;

module.exports = { EMAIL_MAX_ATTEMPTS, PAYMENT_MAX_ATTEMPTS, NOTIFICATION_MAX_ATTEMPTS };
